### ISSUE TITLE
Plastic spacer missing in BOM

### ISSUE THREAD

**Issue by adebree** [nkitanov/iaq_board#1]
Thank you so much for sharing all this information in enormous details. We are planning to build a couple of this for fun, learning and entertainment. I just noticed a plastic spacer in your video between on of the the displays and the PCB. Although technically not needed of course, can you add these to the BOM with the details of the size? Thanks!

**Comment by nkitanov** [comment]
Updated the BOM with the plastic bolts I use. Spacer was some initial idea but never used it.
