### ISSUE TITLE
Second Display linked in BOM does not work correctly

### ISSUE THREAD

**Issue by SyedAmerGilani** [nkitanov/iaq_board#11]
I bought the exact linked display. But i took the v2 Version with the Buttons on the Ali Express site.
The Problem is that it displays the same contents as the first display, regardless which address is configured.

Which looks like this:
![](https://i.imgur.com/T2TKUOO.jpg)

The Display looks like this:
![](https://i.imgur.com/fvaYfr8.jpg)

I even tried removing the  first display completely from the code which just had the effect that none of the displays showed anything.
My current assumption is that those displays are simply bad, but maybe somebody has an input.

Funny thing about the first display is that mine is configurable on the back between 0x78 and 0x7A but it still works with the default addresses.

**Comment by nkitanov** [comment]
It is simple - both displays have the same i2c address. This particular display have a tiny connection between the two pads (I got that info from a friend, never had these displays). Just cut it with a razor and it should work:  

![image](https://user-images.githubusercontent.com/1141799/112035210-0011ba00-8b48-11eb-9890-c579d065b3b4.png)

**Comment by SyedAmerGilani** [comment]
oh :man_facepalming: 
what i thought was what they meant is that those pads should be soldered or unsoldered...
just measured them, yeah they are connected even then unsoldered.
thanks for the input.

**Comment by nkitanov** [comment]
I think I also have one of these somewhere and maybe year ago had the same issue. :) These Chinese parts are like a box of chocolates. You never know what you're gonna get. :)
