### ISSUE TITLE
Import files into EasyEDA

### ISSUE THREAD

**Issue by jcastro** [nkitanov/iaq_board#14]
Hi!
I'm trying to import the Kicad files into EasyEDA but I'm getting an error. I'm not sure if it's the way Kicad export the files or the other way around. Is there any other options for exporting on kicad. Looks like EasyEDA supports these
![Screenshot 2021-07-19 at 17 38 36](https://user-images.githubusercontent.com/190036/126187304-e1353da3-f181-4a1f-aceb-c3fd9a0c1892.png)

**Comment by nkitanov** [comment]
Hi, 

Unfortunatelly I do not have any idea about EasyEDA.

**Comment by jcastro** [comment]
Thanks!
