### ISSUE TITLE
[IDEA] Closed box

### ISSUE THREAD

**Issue by hpapagaj** [nkitanov/iaq_board#2]
Hi,

This is a great project. It would be great to have a closed box for it (maybe for a slimmed version, without LEDs, and displays).

**Comment by nkitanov** [comment]
I do not have time now to design closed box and I use all my devices with the open box, even without box. :)  If anyone wants to cornubite, please let me know to give you permissions to upload.

**Comment by nkitanov** [comment]
Or just make a pull request. :)

**Comment by Dinth** [comment]
+1 from me for closed box
