### ISSUE TITLE
Through board instead of smd

### ISSUE THREAD

**Issue by tyme2tb** [nkitanov/iaq_board#21]
I was wondering how hard it would be to change the design to have through board holes for the D1 Mini, instead of SMD pads? I have not played with trying to design a PCB before.

Thanks

**Comment by tyme2tb** [comment]
closing because I figured it out

**Comment by nkitanov** [comment]
Of course PCB can be modified but if you make through hole connection then yoou can't install beneath it the PMS sensor. Then the PCB will be overall too big.
